name: ny_times
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  json_annotation: 3.0.1
  http:
  http_interceptor:
  shared_preferences:
  cached_network_image:
  intl:
  url_launcher:
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: 3.4.1
  build_runner: 1.10.2


flutter:

  uses-material-design: true

